
package edu.softmap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OiMundoService", targetNamespace = "http://softmap.edu/", wsdlLocation = "http://localhost:8081/oi?wsdl")
public class OiMundoService
    extends Service
{

    private final static URL OIMUNDOSERVICE_WSDL_LOCATION;
    private final static WebServiceException OIMUNDOSERVICE_EXCEPTION;
    private final static QName OIMUNDOSERVICE_QNAME = new QName("http://softmap.edu/", "OiMundoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/oi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OIMUNDOSERVICE_WSDL_LOCATION = url;
        OIMUNDOSERVICE_EXCEPTION = e;
    }

    public OiMundoService() {
        super(__getWsdlLocation(), OIMUNDOSERVICE_QNAME);
    }

    public OiMundoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OIMUNDOSERVICE_QNAME, features);
    }

    public OiMundoService(URL wsdlLocation) {
        super(wsdlLocation, OIMUNDOSERVICE_QNAME);
    }

    public OiMundoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OIMUNDOSERVICE_QNAME, features);
    }

    public OiMundoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OiMundoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OiMundo
     */
    @WebEndpoint(name = "OiMundoPort")
    public OiMundo getOiMundoPort() {
        return super.getPort(new QName("http://softmap.edu/", "OiMundoPort"), OiMundo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OiMundo
     */
    @WebEndpoint(name = "OiMundoPort")
    public OiMundo getOiMundoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://softmap.edu/", "OiMundoPort"), OiMundo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OIMUNDOSERVICE_EXCEPTION!= null) {
            throw OIMUNDOSERVICE_EXCEPTION;
        }
        return OIMUNDOSERVICE_WSDL_LOCATION;
    }

}
